apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }} 
  description: ${{ values.description}}   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=${{  values.name  }}  
  {%- if values.isTekton %}
    janus-idp.io/tekton: ${{ values.name }} 
  {%- endif %}
  {%- if values.isJenkins %}
    jenkins.io/job-full-name: ${{ values.name }} 
  {%- endif %}
    backstage.io/kubernetes-id: ${{ values.name }} 
    backstage.io/techdocs-ref: dir:. 
  {%- if values.image contains "quay.io" %}
    quay.io/repository-slug: ${{ values.repoSlug }}
  {%- elif values.image contains "jfrog" %}
    jfrog-artifactory/image-name: ${{ values.repoSlug }}
  {%- elif values.image contains "nexus" %}
    nexus-repository-manager/docker.image-name: ${{ values.repoSlug }}
  {%- endif %}  
  tags: ${{ values.tags }} 
spec:
  type: service
  owner: ${{ values.owner }} 
  lifecycle: experimental
 